
# This Flex config file references the built-in Acrobat Reader application template.

# DirectFlex is configured and enabled (on the DirectFlex tab) to import personal settings
# when Acrobat Reader is launched and to export settings when it is closed.

[Metadata]
ProcessIfExists=
DirectFlexEnabled
DirectFlexPath=acrord32.exe
ProcessCriteria=<pc ll='0' t='3' f='0' />

[BinarySettings]
oZTQhKWl8ZT5ieWE8JXmuvuY6oXnhvLSgOWE4IX3qJqqmK2dpJWjt7f2kv2f+tqb+Irlh+aSsuCF5IDll5KSsLD4s/Cl+arFo9egwbPWisuvwKLHm9q5y6TGp9PzocSlwaTW9/e/9Lfivu2C5JDnhvSRzYzoh+WA3J35lvSRsfCT4Y7sjfnQ0JjTkMWZyqXDt8Ch07bqq8+gwqf7ut6x07aWxbzSsdmrxKrDudyu8rb19fX09OPj357untq7z66QzI3phuSB3Zz/jeKA4ZWOjrLzg/O31qLD/aHghOuJ7LD8lfuc6YDzh+6N/uTk2Jnpmd28yKmXy4rugeOG2pL3lvKe95D4jP////////8Xb2Z7


[Immidio Flex]
This file was created using Omnissa DEM Management Console version 10.19.0.2389.
Use only with Omnissa DEM.
