
# This Flex config file references the built-in Remote Desktop Connection application template.

# DirectFlex is configured and enabled (on the DirectFlex tab) to import personal settings
# when Remote Desktop Connection is launched and to export settings when it is closed.

[Metadata]
ProcessIfExists=
DirectFlexEnabled
DirectFlexPath=mstsc.exe
ProcessCriteria=<pc ll='0' t='3' f='0' />

[BinarySettings]
vvlvKQUFUTRZKUUkUDVGGkgtQC9bPh5aP0wnUzxMbC9ALkAlRjJbNFoFNwc1ADAJOA4XF0UgTSJWMxNXMkEqXjFBYSJNI00oSz9WOVdSUnx8NH88aTVmCW8bbA1/GkYLYgFzHG8AZhJOGn8NYAlnBmpKGXwOeB1vTwxgCWwCdnZ2dXVjY18PahhrBGoLZ1kFQSRCI1Y6TmASdgYGBgYGBgbx+yAv


[Immidio Flex]
This file was created using Omnissa DEM Management Console version 10.19.0.2389.
Use only with Omnissa DEM.
